In [4]:
import pandas as pd
import os
os.chdir(r'C:\Users\HP\Documents\tesis\Resultados_Python')
Datos =  pd.read_excel('Fiscales_Actual.xlsx', sheet_name= 'Sheet1')
Datos1 = Datos[Datos.PROVINCIA == 'GUAYAS']
df = (Datos1 
  .groupby('CANTÓN')
  .agg(frequency=('CANTÓN', "count")))

df

                         frequency
CANTÓN
BALAO                            1
BALZAR                           1
DAULE                            1
DURAN                            8
EL EMPALME                       2
EL TRIUNFO                       1
GUAYAQUIL                      133
MILAGRO                          8
NARANJAL                         3
PLAYAS                           2
SALITRE                          1
SAMBORONDON                      4
SAN JACINTO DE YAGUACHI          2
SANTA LUCIA                      1